// generated by: https://www.typescriptlang.org/play

export class Reflector_IPC_main {
    constructor(ipcMain: any, msgEnv?: any);
    _msgcache: any;
    _ipcMain: any;
    _windows: Set<any>;
    _msgEnv: any;
    _logr: any;
    _l: any;
    handler_MsgEnv(msg: any): void;
    handler_ipc(event: any, msg: any): void;
    subscribe(): void;
    add_window(win: any): void;
    remove_window(win: any): void;
    set options(arg: any);
}
declare const logr_: any;
export { logr_ as logr };
